name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull talitasanntosdev/cicd-pipeline:latest
      - name: Delete Old docker container
        run: sudo docker rm -f cicd-pipeline-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 5000:5000 --name cicd-pipeline-container talitasanntosdev/cicd-pipeline
