name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: sudo docker pull talitasantosdev/cicd-pipeline:latest

      - name: Run new Docker container
        run: |
          # Run a new container on a different port (e.g., 5001)
          sudo docker run -d -p 5001:5000 --name cicd-pipeline-container-new talitasantosdev/cicd-pipeline:latest

      - name: Wait for new container to be healthy
        run: sleep 30 # Adjust the sleep duration as needed

      - name: Update load balancer to point to the new container
        run: |
          # Update the Nginx configuration to point to the new container
          sudo sed -i 's/5000/5001/' /etc/nginx/conf.d/default.conf
          sudo nginx -s reload

      - name: Remove old Docker container
        run: |
          if [ "$(sudo docker ps -a -q -f name=cicd-pipeline-container)" ]; then
            sudo docker rm -f cicd-pipeline-container
          fi

      - name: Rename new container to the old container name (optional)
        run: sudo docker rename cicd-pipeline-container-new cicd-pipeline-container
