name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: sudo docker pull talitasantosdev/cicd-pipeline:latest

      - name: Ensure port 5001 is free
        run: |
          if lsof -i:5001; then
            sudo kill -9 $(lsof -t -i:5001)
          fi

      - name: Run new Docker container on port 5001
        run: |
          sudo docker run -d -p 5001:5000 --name cicd-pipeline-container-new talitasantosdev/cicd-pipeline:latest

      - name: Wait for new container to be healthy
        run: sleep 20

      - name: Test new deployment on port 5001
        run: |
          curl -f http://127.0.0.1:5001 || exit 1  # Exemplo simples de teste

      - name: Temporarily update nginx (load balancer) to point to port 5001
        run: |
          sudo sed -i 's/server 127.0.0.1:5000;/server 127.0.0.1:5001;/' /etc/nginx/conf.d/default.conf
          sudo nginx -s reload

      - name: Ensure port 5000 is free
        run: |
          if lsof -i:5000; then
            sudo kill -9 $(lsof -t -i:5000)
          fi

      - name: Stop and remove old Docker container if exists
        run: |
          if [ "$(sudo docker ps -a -q -f name=cicd-pipeline-container)" ]; then
            sudo docker stop cicd-pipeline-container || true
            sudo docker rm cicd-pipeline-container || true
          fi

      - name: Run new Docker container on port 5000
        run: |
          sudo docker run -d -p 5000:5000 --name cicd-pipeline-container talitasantosdev/cicd-pipeline:latest

      - name: Wait for container on port 5000 to be healthy
        run: sleep 20

      - name: Test new deployment on port 5000
        run: |
          curl -f http://127.0.0.1:5000 || exit 1  # Exemplo simples de teste

      - name: Update nginx (load balancer) to point back to port 5000
        run: |
          sudo sed -i 's/server 127.0.0.1:5001;/server 127.0.0.1:5000;/' /etc/nginx/conf.d/default.conf
          sudo nginx -s reload

      - name: Stop and remove the Docker container on port 5001
        run: |
          sudo docker stop cicd-pipeline-container-new || true
          sudo docker rm cicd-pipeline-container-new || true
