name: CI Pipeline

on:
  push:
    branches:
      - main
        # O pipeline é acionado quando há um push na branch "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Remove unused Docker images
        run: docker image prune -af

      - name: Build the Docker image
        run: docker build -t talitasantosdev/cicd-pipeline .

      - name: Push to Docker Hub
        run: docker push talitasantosdev/cicd-pipeline:latest
