name: CI Pipeline

on:
  pull_request:
    branches:
      - main
        # O pipeline é acionado quando há um pr na branch "main"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Login Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build image Docker
        run: docker build -t talitasantosdev/cicd-pipeline .

      - name: Push to Docker Hub
        run: docker push talitasantosdev/cicd-pipeline:latest
