name: CI Pipeline

on:
  push:
    branches:
      ["main"]
      # O pipeline é acionado quando há um push na branch "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Faz login no Docker Hub
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      # Constrói a imagem Docker
      - name: Build the Docker image
        run: docker build -t talitasantosdev/cicd-pipeline .

      # Envia a imagem Docker para o Docker Hub
      - name: Push to Dockerhub
        run: docker push talitasantosdev/cicd-pipeline:latest
